import { Product, Category } from './types';

export const categories: Category[] = [
  {
    id: 'all',
    name: 'All',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/78/78921.png',
  },
  {
    id: 'vegetables',
    name: 'Fresh Vegetables',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3142/3142273.png',
  },
  {
    id: 'greens',
    name: 'Greens & Herbs',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/2329/2329903.png',
  },
];

// FIX: Added price property to all product objects to resolve error in Receipt.tsx
export const products: Product[] = [
  {
    id: 1,
    name: 'Tomato',
    tamilName: 'தக்காளி',
    weight: '500 g',
    price: 20,
    imageUrl: 'https://i.imgur.com/4zL6f7u.png',
    category: 'vegetables',
  },
  {
    id: 4,
    name: 'Onion',
    tamilName: 'வெங்காயம்',
    weight: '1 kg',
    price: 40,
    imageUrl: 'https://i.imgur.com/JxgA3Q5.png',
    category: 'vegetables',
  },
  {
    id: 9,
    name: 'Potato',
    tamilName: 'உருளைக்கிழங்கு',
    weight: '1 kg',
    price: 30,
    imageUrl: 'https://i.imgur.com/I2sS21n.png',
    category: 'vegetables',
  },
  {
    id: 10,
    name: 'Brinjal',
    tamilName: 'கத்திரிக்காய்',
    weight: '500 g',
    price: 25,
    imageUrl: 'https://i.imgur.com/jGq8e4m.png',
    category: 'vegetables',
  },
  {
    id: 11,
    name: 'Drumstick',
    tamilName: 'முருங்கைக்காய்',
    weight: '2 pcs',
    price: 15,
    imageUrl: 'https://i.imgur.com/YwNqT8U.png',
    category: 'vegetables',
  },
  {
    id: 12,
    name: 'Ladies Finger',
    tamilName: 'வெண்டைக்காய்',
    weight: '500 g',
    price: 20,
    imageUrl: 'https://i.imgur.com/M5QjL2Q.png',
    category: 'vegetables',
  },
  {
    id: 13,
    name: 'Beans',
    tamilName: 'பீன்ஸ்',
    weight: '500 g',
    price: 35,
    imageUrl: 'https://i.imgur.com/tY73s7Y.png',
    category: 'vegetables',
  },
  {
    id: 14,
    name: 'Carrot',
    tamilName: 'கேரட்',
    weight: '500 g',
    price: 30,
    imageUrl: 'https://i.imgur.com/pTBn8qC.png',
    category: 'vegetables',
  },
  {
    id: 15,
    name: 'Beetroot',
    tamilName: 'பீட்ரூட்',
    weight: '500 g',
    price: 25,
    imageUrl: 'https://i.imgur.com/yFf2N4g.png',
    category: 'vegetables',
  },
  {
    id: 16,
    name: 'Cabbage',
    tamilName: 'முட்டைக்கோஸ்',
    weight: '1 pc',
    price: 20,
    imageUrl: 'https://i.imgur.com/rS254tB.png',
    category: 'vegetables',
  },
  {
    id: 17,
    name: 'Cauliflower',
    tamilName: 'காலிஃபிளவர்',
    weight: '1 pc',
    price: 30,
    imageUrl: 'https://i.imgur.com/QjA8W4X.png',
    category: 'vegetables',
  },
  {
    id: 18,
    name: 'Raw Banana',
    tamilName: 'வாழைக்காய்',
    weight: '2 pcs',
    price: 15,
    imageUrl: 'https://i.imgur.com/8zW3v1G.png',
    category: 'vegetables',
  },
  {
    id: 19,
    name: 'Taro Root',
    tamilName: 'சேப்பங்கிழங்கு',
    weight: '500 g',
    price: 30,
    imageUrl: 'https://i.imgur.com/w1i2z3b.png',
    category: 'vegetables',
  },
  {
    id: 20,
    name: 'Elephant Foot Yam',
    tamilName: 'சேனைக்கிழங்கு',
    weight: '1 kg',
    price: 50,
    imageUrl: 'https://i.imgur.com/pW9j2jL.png',
    category: 'vegetables',
  },
  {
    id: 21,
    name: 'Ash Gourd',
    tamilName: 'பூசணிக்காய்',
    weight: '1 kg',
    price: 25,
    imageUrl: 'https://i.imgur.com/lO8u2iG.png',
    category: 'vegetables',
  },
  {
    id: 22,
    name: 'Chow Chow',
    tamilName: 'சௌ சௌ',
    weight: '500 g',
    price: 20,
    imageUrl: 'https://i.imgur.com/mO3u1uP.png',
    category: 'vegetables',
  },
  {
    id: 23,
    name: 'Ivy Gourd',
    tamilName: 'கோவக்காய்',
    weight: '250 g',
    price: 20,
    imageUrl: 'https://i.imgur.com/tZ2e3jK.png',
    category: 'vegetables',
  },
  {
    id: 24,
    name: 'Cluster Beans',
    tamilName: 'கொத்தவரங்காய்',
    weight: '250 g',
    price: 18,
    imageUrl: 'https://i.imgur.com/7d4w5eF.png',
    category: 'vegetables',
  },
  {
    id: 25,
    name: 'Bottle Gourd',
    tamilName: 'சுரைக்காய்',
    weight: '1 pc',
    price: 25,
    imageUrl: 'https://i.imgur.com/k2j4k5L.png',
    category: 'vegetables',
  },
  {
    id: 26,
    name: 'Ridge Gourd',
    tamilName: 'பீர்க்கங்காய்',
    weight: '500 g',
    price: 30,
    imageUrl: 'https://i.imgur.com/qW6x7yZ.png',
    category: 'vegetables',
  },
  {
    id: 27,
    name: 'Garlic',
    tamilName: 'பூண்டு',
    weight: '100 g',
    price: 25,
    imageUrl: 'https://i.imgur.com/sS4d5eF.png',
    category: 'vegetables',
  },
  {
    id: 28,
    name: 'Ginger',
    tamilName: 'இஞ்சி',
    weight: '100 g',
    price: 20,
    imageUrl: 'https://i.imgur.com/aB3c4dE.png',
    category: 'vegetables',
  },
  {
    id: 29,
    name: 'Green Chillies',
    tamilName: 'பச்சை மிளகாய்',
    weight: '100 g',
    price: 10,
    imageUrl: 'https://i.imgur.com/eF4g5hI.png',
    category: 'vegetables',
  },
  {
    id: 30,
    name: 'Coriander Leaves',
    tamilName: 'கொத்தமல்லி',
    weight: '1 bunch',
    price: 15,
    imageUrl: 'https://i.imgur.com/vF1w2xY.png',
    category: 'greens',
  },
  {
    id: 31,
    name: 'Curry Leaves',
    tamilName: 'கறிவேப்பிலை',
    weight: '1 bunch',
    price: 5,
    imageUrl: 'https://i.imgur.com/hJ5k6lM.png',
    category: 'greens',
  },
  {
    id: 32,
    name: 'Spinach',
    tamilName: 'பாலக் கீரை',
    weight: '1 bunch',
    price: 20,
    imageUrl: 'https://i.imgur.com/yG8h9iJ.png',
    category: 'greens',
  },
  {
    id: 33,
    name: 'Drumstick Leaves',
    tamilName: 'முருங்கை கீரை',
    weight: '1 bunch',
    price: 15,
    imageUrl: 'https://i.imgur.com/oP3q4rS.png',
    category: 'greens',
  },
  {
    id: 34,
    name: 'Arai Keerai',
    tamilName: 'அரைக்கீரை',
    weight: '1 bunch',
    price: 15,
    imageUrl: 'https://i.imgur.com/cW2x3yZ.png',
    category: 'greens',
  },
  {
    id: 35,
    name: 'Siru Keerai',
    tamilName: 'சிறுக்கீரை',
    weight: '1 bunch',
    price: 15,
    imageUrl: 'https://i.imgur.com/uP7g8hJ.png',
    category: 'greens',
  },
];

export const navLinks = [
  { name: 'Why Us', href: '#why-us' },
  { name: 'Products', href: '#products' },
  { name: 'About', href: '#about' },
  { name: 'Contact', href: '#contact' },
];
