import { Product, Category } from './types';

export const categories: Category[] = [
  {
    id: 'all',
    name: 'All',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/78/78921.png',
  },
  {
    id: 'vegetables',
    name: 'Fresh Vegetables',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3142/3142273.png',
  },
  {
    id: 'greens',
    name: 'Greens & Herbs',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/2329/2329903.png',
  },
];

// FIX: Added price property to all product objects to resolve error in Receipt.tsx
export const products: Product[] = [
  {
    id: 1,
    name: 'Tomato',
    tamilName: 'தக்காளி',
    weight: '500 g',
    price: 20,
    imageUrl: 'https://silvaintl.imgix.net/blog/Health-Benefits-Tomatoes.jpg?auto=compress%2Cformat&ch=dpr&cs=srgb&dpr=1&fit=crop&fp-x=0.5&fp-y=0.5&h=375&ixlib=php-3.1.0&q=75&sharp=10&step=100&w=375',
    category: 'vegetables',
  },
  {
    id: 4,
    name: 'Onion',
    tamilName: 'வெங்காயம்',
    weight: '1 kg',
    price: 40,
    imageUrl: 'https://plantix.net/en/library/assets/custom/crop-images/onion.jpeg',
    category: 'vegetables',
  },
  {
    id: 9,
    name: 'Potato',
    tamilName: 'உருளைக்கிழங்கு',
    weight: '1 kg',
    price: 30,
    imageUrl: 'https://cdn.mos.cms.futurecdn.net/iC7HBvohbJqExqvbKcV3pP.jpg',
    category: 'vegetables',
  },
  {
    id: 10,
    name: 'Brinjal',
    tamilName: 'கத்திரிக்காய்',
    weight: '500 g',
    price: 25,
    imageUrl: 'https://pushtiorganics.com/cdn/shop/files/Brinjal_d2d7db50-62dd-4b99-af45-9f0adf46703d_1200x.png?v=1709270808',
    category: 'vegetables',
  },
  {
    id: 11,
    name: 'Drumstick',
    tamilName: 'முருங்கைக்காய்',
    weight: '2 pcs',
    price: 15,
    imageUrl: 'https://healthy-indian.com/wp-content/uploads/2017/08/drumsticks-600-x-450.jpg',
    category: 'vegetables',
  },
  {
    id: 12,
    name: 'Ladies Finger',
    tamilName: 'வெண்டைக்காய்',
    weight: '500 g',
    price: 20,
    imageUrl: 'https://d3kgrlupo77sg7.cloudfront.net/media/l3-grocery2.shopnix.org/images/products/hypercity-fresh-sweet-lime-loose1-v-500-g.20171011123502.webp',
    category: 'vegetables',
  },
  {
    id: 13,
    name: 'Beans',
    tamilName: 'பீன்ஸ்',
    weight: '500 g',
    price: 35,
    imageUrl: 'https://vgrgardens.com/wp-content/uploads/2024/11/Bush-Beans-%E0%AE%AA%E0%AF%80%E0%AE%A9%E0%AF%8D%E0%AE%B8%E0%AF%8D.jpg',
    category: 'vegetables',
  },
  {
    id: 14,
    name: 'Carrot',
    tamilName: 'கேரட்',
    weight: '500 g',
    price: 30,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTba3FfUO6CI9cySnHdGt1roZY60bdUInxLXQ&s',
    category: 'vegetables',
  },
  {
    id: 15,
    name: 'Beetroot',
    tamilName: 'பீட்ரூட்',
    weight: '500 g',
    price: 25,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSKE2uRnre8_xM7xsYy4U6_EvxcD7WGhNySg&s',
    category: 'vegetables',
  },
  {
    id: 16,
    name: 'Cabbage',
    tamilName: 'முட்டைக்கோஸ்',
    weight: '1 pc',
    price: 20,
    imageUrl: 'https://www.koppert.com/content/_processed_/0/4/csm_Cabbage_39513da9af.jpg',
    category: 'vegetables',
  },
  {
    id: 17,
    name: 'Cauliflower',
    tamilName: 'காலிஃபிளவர்',
    weight: '1 pc',
    price: 30,
    imageUrl: 'https://thriftylesley.com/wp-content/uploads/2013/09/cauliflower.jpg',
    category: 'vegetables',
  },
  {
    id: 18,
    name: 'Raw Banana',
    tamilName: 'வாழைக்காய்',
    weight: '2 pcs',
    price: 15,
    imageUrl: 'https://thevegetablebazaar.in/wp-content/uploads/2022/04/Raw-Banana-1.png',
    category: 'vegetables',
  },
  {
    id: 19,
    name: 'Taro Root',
    tamilName: 'சேப்பங்கிழங்கு',
    weight: '500 g',
    price: 30,
    imageUrl: 'https://cdn.pixabay.com/photo/2020/07/03/23/52/taro-5367857_1280.jpg',
    category: 'vegetables',
  },
  {
    id: 20,
    name: 'Elephant Foot Yam',
    tamilName: 'சேனைக்கிழங்கு',
    weight: '1 kg',
    price: 50,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxdDIPlQJ4SQF1Mvu4N1KZZacuqK1lIj2kJA&s',
    category: 'vegetables',
  },
  {
    id: 21,
    name: 'Ash Gourd',
    tamilName: 'பூசணிக்காய்',
    weight: '1 kg',
    price: 25,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRf3MnjhZsPQjq9dQDQ0rD_9dPQE-DLimcZD0Y67qNCzCGUjDW1UBC_2XAALjnpL2L00nM&usqp=CAU',
    category: 'vegetables',
  },
  {
    id: 22,
    name: 'Chow Chow',
    tamilName: 'சௌ சௌ',
    weight: '500 g',
    price: 20,
    imageUrl: 'https://img.cdnx.in/313405/1697191214070_1.jpeg?width=600&format=webp',
    category: 'vegetables',
  },
  {
    id: 23,
    name: 'Ivy Gourd',
    tamilName: 'கோவக்காய்',
    weight: '250 g',
    price: 20,
    imageUrl: 'https://www.chefadora.com/_next/image?url=https%3A%2F%2Fchefadora.b-cdn.net%2Fmedium_ingredient_ivy_gourd_8c875b5ca5.png&w=3840&q=75',
    category: 'vegetables',
  },
  {
    id: 24,
    name: 'Cluster Beans',
    tamilName: 'கொத்தவரங்காய்',
    weight: '250 g',
    price: 18,
    imageUrl: 'https://parajorganics.com/wp-content/uploads/2019/12/10000040_9-fresho-beans-cluster.jpg',
    category: 'vegetables',
  },
  {
    id: 25,
    name: 'Bottle Gourd',
    tamilName: 'சுரைக்காய்',
    weight: '1 pc',
    price: 25,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbYsouO0sXEJ7gb2CCjyxGvVmQqE6Ef9WVyQ&s',
    category: 'vegetables',
  },
  {
    id: 26,
    name: 'Ridge Gourd',
    tamilName: 'பீர்க்கங்காய்',
    weight: '500 g',
    price: 30,
    imageUrl: 'https://organicmandya.com/cdn/shop/files/RidgeGourd.jpg?v=1757083841&width=1500',
    category: 'vegetables',
  },
  {
    id: 27,
    name: 'Garlic',
    tamilName: 'பூண்டு',
    weight: '100 g',
    price: 25,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyDu52_BDOwZwQvBUDi6eOByiAxeGOVZ-JrA&s',
    category: 'vegetables',
  },
  {
    id: 28,
    name: 'Ginger',
    tamilName: 'இஞ்சி',
    weight: '100 g',
    price: 20,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvd0WlROys2ivv0ozprQ-EmTwPydVZKRyggw&s',
    category: 'vegetables',
  },
  {
    id: 29,
    name: 'Green Chillies',
    tamilName: 'பச்சை மிளகாய்',
    weight: '100 g',
    price: 10,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp9VtSlERy6gCbVNDIOpnBVIEU7Zdj7qyA7A&s',
    category: 'vegetables',
  },
  {
    id: 30,
    name: 'Coriander Leaves',
    tamilName: 'கொத்தமல்லி',
    weight: '1 bunch',
    price: 15,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQa86r18PngCfFZhZUwAXHc9vkNioB4odaFEw&s',
    category: 'greens',
  },
  {
    id: 31,
    name: 'Curry Leaves',
    tamilName: 'கறிவேப்பிலை',
    weight: '1 bunch',
    price: 5,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSk5UftAnEuC7YHdcaaH7Pn4xOh1zj1ReZ4g&s',
    category: 'greens',
  },
  {
    id: 32,
    name: 'Spinach',
    tamilName: 'பாலக் கீரை',
    weight: '1 bunch',
    price: 20,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp1kl3tKNy9LXFTJFcxa-2pzzvVG552fJcaw&s',
    category: 'greens',
  },
  {
    id: 33,
    name: 'Drumstick Leaves',
    tamilName: 'முருங்கை கீரை',
    weight: '1 bunch',
    price: 15,
    imageUrl: 'https://mydiagnostics.in/cdn/shop/articles/img-1749111538563_a4eeaff4-ad76-4019-97c5-ff36a62caf12_1200x.jpg?v=1754660056',
    category: 'greens',
  },
  {
    id: 34,
    name: 'Arai Keerai',
    tamilName: 'அரைக்கீரை',
    weight: '1 bunch',
    price: 15,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl4PGUqLI5zdId9plM0jP0DJw--SHBGA_Pgw&s',
    category: 'greens',
  },
  {
    id: 35,
    name: 'Siru Keerai',
    tamilName: 'சிறுக்கீரை',
    weight: '1 bunch',
    price: 15,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBKfP14bMsW_i4vmwD2jXH-b-pWy2Gua1Wkg&s',
    category: 'greens',
  },
];

export const navLinks = [
  { name: 'Why Us', href: '#why-us' },
  { name: 'Products', href: '#products' },
  { name: 'About', href: '#about' },
  { name: 'Contact', href: '#contact' },
];
